name: arbicon
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python=3.6
  - pandas=0.23.4
  - scikit-image=0.14.0
  - numba=0.41.0
  - opencv=3.4.2
  - pytorch=0.2.0
  - scikit-learn=0.20.1
  - torchvision
  - requests
  - click